### ISSUE TITLE
Create Issue buttons

### ISSUE THREAD

**Issue by dakshsinghrathore** [dashroshan/coding-contests-companion#62]
Currently the contributor has to raise an issue from ground zero without any ***prebuilt buttons***, to gain a better understanding of the issue raised we can create custom issue buttons which will be ***visually appealing*** as well ***hassle free*** for the contributor to express their concern in an ***ordered manner*** .
 Here 👇 are some screenshots attached to give you a better understanding on what am up to 
### Currently

![Screenshot 2023-06-13 at 23-14-43 New Issue · SrijanShovit_carbonops-v2](https://github.com/SrijanShovit/carbonops-v2/assets/115932772/66a1f488-b745-4124-a218-92bbbc7307ef)

### To Come

![Screenshot 2023-06-13 at 23-19-39 New Issue · priyankarpal_ProjectsHut](https://github.com/SrijanShovit/carbonops-v2/assets/115932772/42addc33-f9fb-4eaf-b60a-fb7dab74844c)

**Comment by dakshsinghrathore** [comment]
Kindly assign this issue to me @roshan1337d

**Comment by roshan1337d** [comment]
@dakshsinghrathore go ahead, assigned it to you 👍

**Comment by dakshsinghrathore** [comment]
Hey @roshan1337d I would also like to add respective issue forms to every button, it will not be easy for the contributor to raise an issue also it will be visually pleasing for the admin to go through the issue hassle free. 👇

![Screenshot 2023-06-23 at 21-22-39 New Issue · dakshsinghrathore_htmltut](https://github.com/roshan1337d/coding-contests-companion/assets/115932772/82936b04-6272-4660-b3e7-38eb5728d6b0)
